GET http://localhost:8080/api/fixtureruns
content-type: application/json
###
GET http://localhost:8080/api/fixturerun/fixtureRunId1
content-type: application/json
###
POST http://localhost:8080/api/fixturerun/
content-type: application/json

{
  "fixtureRunId": "fixtureRunId1",
  "targetBranches": [
    {
      "repo": "Xactimate.Android",
      "name": "bugfix/branchA",
      "commit":"234234234234"
    },
    {
      "repo": "Xactimate.Shared",
      "name": "bugfix/BranchB",
      "commit":"w452345345"
    }
  ],
  "start": 123456,
  "end": 123459,
  "automationAgent": "Agent6"
}

###
GET http://localhost:8080/api/fixturerun/fixtureRunId1/testruns
content-type: application/json
###
GET http://localhost:8080/api/testrun/testRunId1
content-type: application/json
###
POST http://localhost:8080/api/testrun/
content-type: application/json

{"testRunId": "testRunId1", "fixtureRunId": "fixtureRunId1", "start": 1234, "end": 12345, "testParams": "asdfasdf", "videoURL": "asdf", "testStatus": "Pass"}
###
GET http://localhost:8080/api/testrun/testRunId1/steps
content-type: application/json
###
GET http://localhost:8080/api/teststep/testStepId1
content-type: application/json
###
POST http://localhost:8080/api/teststep/
content-type: application/json

{
  "testStepId": "testStepId1",
  "testRunId": "testRunId1",
  "action": "Click",
  "actionParams": "",
  "beforeImageURL": "imageURL",
  "elementFindBy": "id",
  "elementLocator": "_asdf",
  "actionStart": 12345,
  "actionEnd": 123456,
  "failedReason": "idk",
  "foundElementImageURL": "elementImageURL",
  "imageOfElement": "image",
  "pageClassName": "ProfilePage",
  "elementPropertyName": "NextButton",
  "sourceFileName": "ProfilePage.cs",
  "sourceLineNumber": 12,
  "targetProcessMemoryUsage": 1234,
  "testMemoryUsage": 123
}
###


